/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#ffffff",
        "primary-container": "#c3f400",
        "primary-fixed": "#c3f400",
        "primary-fixed-dim": "#abd600",
        "on-primary": "#283500",
        "on-primary-fixed": "#161e00",
        "on-primary-fixed-variant": "#3c4d00",
        "on-primary-container": "#556d00",
        "inverse-primary": "#506600",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c9ac",
        secondary: "#bdf4ff",
        "secondary-fixed": "#9cf0ff",
        "secondary-fixed-dim": "#00daf3",
        "secondary-container": "#00e3fd",
        "on-secondary": "#00363d",
        "on-secondary-fixed-variant": "#004f58",
        "on-secondary-container": "#00616d",
        tertiary: "#ffffff",
        "tertiary-fixed-dim": "#b6c9d8",
        "on-tertiary": "#21323e",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        outline: "#8e9379",
        "outline-variant": "#444933",
        accent: "#c3f400",
        mint: "#2DD4A8",
        coral: "#FF6B52",
        rose: "#F43F5E",
        sky: "#38BDF8",
      },
      fontFamily: {
        display: ["Inter_700Bold", "Inter_800ExtraBold"],
        headline: ["Inter_700Bold"],
        body: ["Inter_400Regular"],
        "body-bold": ["Inter_700Bold"],
        stats: ["SpaceGrotesk_600SemiBold", "SpaceGrotesk_700Bold"],
        "label-caps": ["SpaceGrotesk_700Bold"],
        "label-caps-semibold": ["SpaceGrotesk_600SemiBold"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "stats-xl": ["40px", { lineHeight: "40px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        "container-padding": "20px",
        "stack-gap": "12px",
        "section-gap": "32px",
        "touch-target": "44px",
        unit: "4px",
      },
      borderRadius: {
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
